---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wellington
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wellington
    spec:
      containers:
        - name: wellington
          image: gcr.io/discord-bots-217700/wellington:latest
          imagePullPolicy: Always
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wellington-config
                  key: discord-token
          resources:
            requests:
              cpu: 10m
              memory: 10M
            limits:
              cpu: 20m
              memory: 20M